# Generated by Django 5.0.1 on 2024-05-22 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_no',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False),
        ),
    ]
